version: '3.1'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: postgresdb
      POSTGRES_USER: user_db
      POSTGRES_PASSWORD: user_db_321
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

volumes:
  postgres-data: